export const ar = {
  brand: "رزق",
  title: "رادار السيولة والزخم",
  subtitle: "إشارات الدخول والخروج من صافي تدفق الأموال والضغط العدواني فقط",
  tape: "شريط السيولة اللحظي",
  radarTitle: "رادار السيولة والزخم (اكتشاف الفرص)",
  radarHint: "أسهم خارج قائمتك يتجاوز فيها صافي التدفق وحدّ الشراء/البيع العدواني",
  radarHintCompliant: "النقية والمختلطة فقط — الأسهم المحرّمة مستبعدة تلقائياً من الرادار",
  radarEmpty: "لا توجد إشارات موثّقة بعد — ننتظر صافي تدفق وعدوانية شراء أو بيع",
  watchlistTitle: "قائمة المتابعة الشخصية",
  watchlistHint: "أضف رمز تداول من 4 أرقام. الأسهم المحرّمة تُرفض تلقائياً، والشارات تظهر بعد تحقق التدفق.",
  addSymbol: "إضافة",
  symbolPlaceholder: "4030",
  remove: "إزالة",
  select: "عرض الشريط",
  entryBadge: "إشارة دخول 🚀",
  exitBadge: "إشارة خروج / تصريف ⚠️",
  waitingFlow: "بانتظار تدفق موثّق",
  buyPressure: "ضغط الشراء",
  sellPressure: "ضغط البيع",
  soundOn: "الصوت مفعّل",
  soundOff: "الصوت مكتوم",
  enableSound: "تفعيل التنبيه الصوتي",
  delayed: "بيانات مؤجلة 15 دقيقة",
  liveData: "بيانات لحظية",
  scanned: "أسهم ممسوحة",
  advancing: "صاعد",
  declining: "هابط",
  netFlow: "صافي تدفق السيولة",
  buy: "إجمالي الشراء (سيولة داخلة)",
  sell: "إجمالي البيع (سيولة خارجة)",
  buyHint: "تدفقات شرائية عدوانية",
  sellHint: "تدفقات بيعية عدوانية",
  accumulation: "تراكم سيولة (إيجابي)",
  distribution: "تصريف (سلبي)",
  neutral: "توازن",
  regime: "حالة السوق",
  accumulationDesc: "المشترون يرفعون الأسعار بقوة",
  distributionDesc: "البائعون يضغطون على الأسعار بقوة",
  neutralDesc: "بانتظار إشارة اتجاه واضحة",
  connected: "متصل",
  connecting: "جاري الاتصال",
  reconnecting: "جاري الاتصال",
  offline: "غير متصل",
  lastPrice: "آخر سعر",
  prints: "صفقة",
  outflow: "تدفق خارج",
  inflow: "تدفق داخل",
  notional: "القيمة الاسمية",
  lastBuy: "آخر تنفيذ: شراء",
  lastSell: "آخر تنفيذ: بيع",
  noPrint: "لا توجد تذكرة مصنّفة بعد",
  attempt: "محاولة",
  alertsTitle: "سجل التنبيهات اللحظية",
  noAlerts: "لا توجد تنبيهات بعد — بانتظار ارتفاع السيولة",
  enablePush: "تفعيل تنبيهات المتصفح",
  pushEnabled: "تنبيهات المتصفح مفعّلة",
  pushDenied: "تم رفض إذن التنبيهات",
  windowLabel: "خلال دقيقة",
  entryPriceLabel: "إشارة دخول بسعر مقترح",
  exitPriceLabel: "خروج موصى به عند",
  target: "الهدف",
  stopLoss: "وقف الخسارة",
  vwap: "VWAP",
  atr: "ATR",
  bookPressure: "ضغط الدفتر",
  addFailed: "تعذر إضافة الرمز — استخدم 4 أرقام مثل 4030",
  watchlistEmpty: "أضف رمزاً للبدء",
  tableSearch: "بحث بالرمز أو اسم الشركة أو القطاع",
  tableFilterAll: "الكل",
  tableFilterPure: "نقي",
  tableFilterMixed: "مختلط",
  tableColCompany: "الشركة",
  tableColStatus: "التصنيف",
  tableColSector: "القطاع",
  tableColPurification: "نسبة التطهير",
  tableColDebt: "نسبة الديون",
  tableColImpure: "الدخل غير النقي",
  tableColQuarter: "الربع",
  tableColFlow: "صافي التدفق",
  tableEmpty: "لا توجد أسهم مطابقة لبحثك أو الفلتر الحالي",
  tableSample: "تصنيف استرشادي لكل شركات السوق — ليس فتوى، ويُحدَّث مع كل ربع",
  tableCount: "سهم ضمن الرادار",
  tableShowList: "إظهار قائمة الشركات",
  tableHideList: "إخفاء القائمة",
  tablePure: "نقي",
  tableMixed: "مختلط",
  tableNoPurification: "لا تطهير",
  radarDemoTitle: "تجربة رادار الأسهم",
  radarDemoHint: "جلب الأسهم النقية والمختلطة من قاعدة البيانات الشرعية وعرضها في الجدول",
  radarBack: "العودة للوحة",
  radarRetry: "إعادة المحاولة",
  radarNotConfigured: "تعذر تحميل قاعدة التصنيف الشرعي. أعد المحاولة بعد قليل.",
  radarLoadError: "تعذر جلب تصنيف الأسهم الشرعية. أعد المحاولة بعد قليل.",
  liveRadarTitle: "رادار السيولة من Sahm",
  liveRadarHint: "يُجلب تحليل الرمز تلقائياً من Sahm دون إرسال شموع من الواجهة",
  liveRadarSource: "المصدر: Sahm API",
  liveRadarLoading: "جاري جلب الشموع من Sahm…",
  liveRadarEmpty: "تعذر جلب بيانات هذا الرمز من Sahm",
  liveRadarNeutral: "لا إشارة مؤكدة حالياً",
  liveRadarTrap: "فخ سيولة",
  rankingEyebrow: "مصفوفة تصنيف الشركات",
  rankingTitle: "مصفوفة تصنيف شركات السوق السعودي (تاسي)",
  rankingHint: "فرز تنازلي يعتمد على النمو، التوزيعات، الملاءة، واستبعاد الخسائر",
  rankingReveal: "اكتشف ترتيب الشركات الأفضل ⚡",
  rankingHide: "إخفاء مصفوفة التصنيف 🔒",
  rankingLoading: "جاري الفرز والمعالجة...",
  rankingLoadError: "تعذر جلب ترتيب الشركات. أعد المحاولة بعد قليل.",
  rankingEmpty: "لا توجد شركات في المصفوفة حالياً",
  rankingHidden: "النتائج مخفية لحين الضغط على الزر أعلاه لعرض مصفوفة التصنيف والفرز المالي المتقدم.",
  rankingColScore: "النقاط",
  rankingColCategory: "التصنيف الهرمي",
  rankingColGrowth: "نمو الأرباح",
  rankingColDividend: "عائد التوزيع",
  rankingColPe: "مكرر الربحية P/E",
  heatmapTitle: "خريطة السيولة القطاعية والتحليل الفردي",
  heatmapHint: "منظومة ترابط ذكية: من نبض القطاع العام إلى فحص السيولة اللحظية للسهم",
  heatmapLive: "تحديث مباشر 🟢",
  heatmapLoading: "جاري تحميل خريطة السيولة القطاعية...",
  heatmapError: "تعذر تحميل الخريطة الحرارية",
  heatmapLoadError: "فشل في جلب بيانات السيولة القطاعية",
  heatmapEmpty: "لا توجد بيانات قطاعات حالياً",
  heatmapAvgChange: "متوسط التغير:",
  heatmapValue: "التداول الإجمالي:",
  heatmapMillion: "مليون ر.س",
  heatmapCompanies: "عدد الشركات بالقطاع:",
  heatmapCompaniesUnit: "شركات",
  heatmapMomentum: "مؤشر الزخم المالي",
  heatmapClickHint: "انقر على أي قطاع لعرض شركاته ومؤشرات السيولة",
  heatmapClickCta: "انقر لعرض شركات القطاع",
  heatmapBack: "← العودة لكل القطاعات",
  heatmapPanelTitle: "شركات قطاع",
  heatmapPanelClose: "إغلاق",
  heatmapPanelLoading: "جاري جلب أسهم الشركات التابعة للقطاع...",
  heatmapPanelEmpty: "لا توجد شركات ظاهرة لهذا القطاع حالياً",
  heatmapPanelError: "تعذر جلب شركات القطاع",
  heatmapColSymbol: "رمز السهم",
  heatmapColCompany: "اسم الشركة",
  heatmapColChange: "التغير السعري",
  heatmapColNetFlow: "صافي التدفق",
  heatmapColInflow: "سيولة داخلة",
  heatmapColOutflow: "سيولة خارجة",
  heatmapColValue: "قيمة التداول",
  heatmapColStatus: "حالة السيولة",
  heatmapColAction: "الإجراء",
  heatmapOpenRadar: "فتح رادار السيولة ⚡",
  heatmapCompaniesHint: "انقر على السهم لفحص السيولة",
  heatmapBackToCompanies: "← العودة لجدول شركات القطاع",
  heatmapRadarLiveHint: "تحليل السيولة اللحظية المباشر",
  recoTitle: "رصد التوصيات والفرص اللحظية",
  recoHint: "فرص الارتداد الإيجابي واستمرار الزخم الصاعد بناءً على أسعار الإغلاق وتدفق السيولة",
  recoLive: "محدث آلياً ⚡",
  recoScan: "مسح السوق الآن",
  recoRefresh: "إعادة المسح",
  recoLoading: "جاري المسح...",
  recoLoadingDetail: "جاري مسح السوق واكتشاف فرص الارتداد واستمرار الصعود بناءً على أسعار الإغلاق...",
  recoIdle: "اضغط لمسح السوق وعرض الفرص المرصودة",
  recoEmpty: "لا توجد فرص ارتداد أو زخم مؤكدة في المسح الحالي",
  recoLoadError: "تعذر جلب توصيات الفرص. أعد المحاولة بعد قليل.",
  recoFilterAll: "كل الفرص",
  recoFilterBounce: "ارتداد إيجابي",
  recoFilterMomentum: "استمرار زخم",
  recoColSymbol: "الرمز",
  recoColSignal: "نوع الإشارة",
  recoColClose: "الإغلاق",
  recoColEntry: "سعر الدخول",
  recoColConfidence: "الثقة",
  recoReason: "المبرر الفني والسيولة",
  marketRadarTitle: "رادار الأسهم الفردية",
  marketRadarHint: "تحليل لحظي لأسهم قائدة بجانب خريطة تدوير السيولة القطاعية",
  tabsTitle: "منصة رادار السيولة والأسواق - رزق",
  tabsWelcome: "مرحباً بك أبو نايف. النظام المتقدم لتتبع السيولة المؤسسية، كشف الفخاخ، وتصنيف شركات تاسي",
  tabsMarketLive: "السوق السعودي (تاسي) - متصل حياً",
  tabsSectors: "خريطة السيولة القطاعية",
  tabsRadar: "رادار السيولة الفردية",
  tabsRecommendations: "توصيات الفرص اللحظية",
  tabsRanking: "مصفوفة تصنيف الشركات",
  prohibitedBlocked: "هذا السهم محرّم ولا يُعرض في رادار السيولة",
  authTitle: "دخول رادار رزق",
  authPinLabel: "الرقم السري",
  authEnter: "دخول",
  authLogout: "خروج",
  authForgot: "نسيت الرقم السري؟",
  authRecoverHint: "سيُرسل رمز الاستعادة إلى",
  authEmailLabel: "البريد الإلكتروني",
  authSendCode: "إرسال رمز الاستعادة",
  authBackToLogin: "العودة لتسجيل الدخول",
  authCodeLabel: "رمز الاستعادة",
  authNewPinLabel: "الرقم السري الجديد",
  authConfirmPinLabel: "تأكيد الرقم السري",
  authSavePin: "حفظ الرقم السري",
  authWrongPin: "الرقم السري غير صحيح",
  authRecoverEmailMismatch: "استخدم بريد الاستعادة المسجّل alhwez@gmail.com",
  authRecoverSent: "أُرسل رمز الاستعادة إلى alhwez@gmail.com",
  authRecoverQueued: "جُهّز رمز الاستعادة. أكّد رسالة FormSubmit الأولى على alhwez@gmail.com إن طُلب ذلك",
  authResetFailed: "رمز الاستعادة غير صالح أو منتهٍ",
  authChangePin: "تعديل الرقم السري",
  authChangePinHint: "أدخل الرقم الحالي ثم الرقم الجديد من 4 إلى 8 أرقام",
  authCurrentPinLabel: "الرقم السري الحالي",
  authPinUpdated: "تم تحديث الرقم السري",
  authChangeFailed: "تعذر تغيير الرقم السري — تحقق من الرقم الحالي وتطابق التأكيد",
  authClose: "إغلاق",
} as const;
