export const ar = {
  brand: "رزق",
  title: "رادار السيولة والزخم",
  subtitle: "إشارات الدخول والخروج من صافي تدفق الأموال والضغط العدواني فقط",
  tape: "شريط السيولة اللحظي",
  radarTitle: "رادار السيولة والزخم (اكتشاف الفرص)",
  radarHint: "أسهم خارج قائمتك يتجاوز فيها صافي التدفق وحدّ الشراء/البيع العدواني",
  radarEmpty: "لا توجد إشارات موثّقة بعد — ننتظر صافي تدفق وعدوانية شراء أو بيع",
  watchlistTitle: "قائمة المتابعة الشخصية",
  watchlistHint: "أضف رمز تداول من 4 أرقام. الشارات تظهر فقط بعد تحقق التدفق.",
  addSymbol: "إضافة",
  symbolPlaceholder: "4030",
  remove: "إزالة",
  select: "عرض الشريط",
  entryBadge: "إشارة دخول 🚀",
  exitBadge: "إشارة خروج / تصريف ⚠️",
  waitingFlow: "بانتظار تدفق موثّق",
  buyPressure: "ضغط الشراء",
  sellPressure: "ضغط البيع",
  soundOn: "الصوت مفعّل",
  soundOff: "الصوت مكتوم",
  enableSound: "تفعيل التنبيه الصوتي",
  delayed: "بيانات مؤجلة 15 دقيقة",
  liveData: "بيانات لحظية",
  scanned: "أسهم ممسوحة",
  advancing: "صاعد",
  declining: "هابط",
  netFlow: "صافي تدفق السيولة",
  buy: "إجمالي الشراء (سيولة داخلة)",
  sell: "إجمالي البيع (سيولة خارجة)",
  buyHint: "تدفقات شرائية عدوانية",
  sellHint: "تدفقات بيعية عدوانية",
  accumulation: "تراكم سيولة (إيجابي)",
  distribution: "تصريف (سلبي)",
  neutral: "توازن",
  regime: "حالة السوق",
  accumulationDesc: "المشترون يرفعون الأسعار بقوة",
  distributionDesc: "البائعون يضغطون على الأسعار بقوة",
  neutralDesc: "بانتظار إشارة اتجاه واضحة",
  connected: "متصل",
  connecting: "جاري الاتصال",
  reconnecting: "جاري الاتصال",
  offline: "غير متصل",
  lastPrice: "آخر سعر",
  prints: "صفقة",
  outflow: "تدفق خارج",
  inflow: "تدفق داخل",
  notional: "القيمة الاسمية",
  lastBuy: "آخر تنفيذ: شراء",
  lastSell: "آخر تنفيذ: بيع",
  noPrint: "لا توجد تذكرة مصنّفة بعد",
  attempt: "محاولة",
  alertsTitle: "سجل التنبيهات اللحظية",
  noAlerts: "لا توجد تنبيهات بعد — بانتظار ارتفاع السيولة",
  enablePush: "تفعيل تنبيهات المتصفح",
  pushEnabled: "تنبيهات المتصفح مفعّلة",
  pushDenied: "تم رفض إذن التنبيهات",
  windowLabel: "خلال دقيقة",
  entryPriceLabel: "إشارة دخول بسعر مقترح",
  exitPriceLabel: "خروج موصى به عند",
  target: "الهدف",
  stopLoss: "وقف الخسارة",
  vwap: "VWAP",
  atr: "ATR",
  bookPressure: "ضغط الدفتر",
  addFailed: "تعذر إضافة الرمز — استخدم 4 أرقام مثل 4030",
  watchlistEmpty: "أضف رمزاً للبدء",
} as const;
